#!/usr/bin/env bash
set -euo pipefail

ASTERISK_REQUIRE_UNIFI="${ASTERISK_REQUIRE_UNIFI:-true}"

ASTERISK_ARI_USERNAME="${ASTERISK_ARI_USERNAME:-dograh}"
ASTERISK_ARI_PASSWORD="${ASTERISK_ARI_PASSWORD:-}"
ASTERISK_STASIS_APP="${ASTERISK_STASIS_APP:-dograh}"
ASTERISK_HTTP_BINDADDR="${ASTERISK_HTTP_BINDADDR:-0.0.0.0}"
ASTERISK_HTTP_PORT="${ASTERISK_HTTP_PORT:-8088}"
ASTERISK_WS_CLIENT_NAME="${ASTERISK_WS_CLIENT_NAME:-dograh}"
DOGRAH_ARI_WS_URI="${DOGRAH_ARI_WS_URI:-ws://127.0.0.1:8000/api/v1/telephony/ws/ari}"
ASTERISK_WS_TLS_ENABLED="${ASTERISK_WS_TLS_ENABLED:-no}"
ASTERISK_PJSIP_BINDADDR="${ASTERISK_PJSIP_BINDADDR:-0.0.0.0}"
ASTERISK_PJSIP_PORT="${ASTERISK_PJSIP_PORT:-5060}"
ASTERISK_EXTERNAL_SIGNALING_ADDRESS="${ASTERISK_EXTERNAL_SIGNALING_ADDRESS:-${ASTERISK_EXTERNAL_ADDRESS:-}}"
ASTERISK_EXTERNAL_MEDIA_ADDRESS="${ASTERISK_EXTERNAL_MEDIA_ADDRESS:-${ASTERISK_EXTERNAL_ADDRESS:-}}"
ASTERISK_LOCAL_NET="${ASTERISK_LOCAL_NET:-}"
ASTERISK_PJSIP_EXTERNAL_SIGNALING_LINE=""
ASTERISK_PJSIP_EXTERNAL_MEDIA_LINE=""
ASTERISK_PJSIP_LOCAL_NET_LINE=""
ASTERISK_RTP_START="${ASTERISK_RTP_START:-10000}"
ASTERISK_RTP_END="${ASTERISK_RTP_END:-20000}"
UNIFI_TALK_ENDPOINT="${UNIFI_TALK_ENDPOINT:-unifi-talk}"
UNIFI_TALK_INBOUND_CONTEXT="${UNIFI_TALK_INBOUND_CONTEXT:-from-unifi-talk}"
UNIFI_TALK_OUTBOUND_CONTEXT="${UNIFI_TALK_OUTBOUND_CONTEXT:-from-dograh}"
UNIFI_TALK_SIP_SERVER="${UNIFI_TALK_SIP_SERVER:-}"
UNIFI_TALK_SIP_PORT="${UNIFI_TALK_SIP_PORT:-5060}"
UNIFI_TALK_SIP_USERNAME="${UNIFI_TALK_SIP_USERNAME:-}"
UNIFI_TALK_SIP_PASSWORD="${UNIFI_TALK_SIP_PASSWORD:-}"
DOGRAH_INBOUND_EXTENSION="${DOGRAH_INBOUND_EXTENSION:-7000}"

export ASTERISK_ARI_USERNAME
export ASTERISK_ARI_PASSWORD
export ASTERISK_STASIS_APP
export ASTERISK_HTTP_BINDADDR
export ASTERISK_HTTP_PORT
export ASTERISK_WS_CLIENT_NAME
export DOGRAH_ARI_WS_URI
export ASTERISK_WS_TLS_ENABLED
export ASTERISK_PJSIP_BINDADDR
export ASTERISK_PJSIP_PORT
export ASTERISK_EXTERNAL_SIGNALING_ADDRESS
export ASTERISK_EXTERNAL_MEDIA_ADDRESS
export ASTERISK_LOCAL_NET
if [[ -n "${ASTERISK_EXTERNAL_SIGNALING_ADDRESS}" ]]; then
    ASTERISK_PJSIP_EXTERNAL_SIGNALING_LINE="external_signaling_address = ${ASTERISK_EXTERNAL_SIGNALING_ADDRESS}"
fi
if [[ -n "${ASTERISK_EXTERNAL_MEDIA_ADDRESS}" ]]; then
    ASTERISK_PJSIP_EXTERNAL_MEDIA_LINE="external_media_address = ${ASTERISK_EXTERNAL_MEDIA_ADDRESS}"
fi
if [[ -n "${ASTERISK_LOCAL_NET}" ]]; then
    ASTERISK_PJSIP_LOCAL_NET_LINE="local_net = ${ASTERISK_LOCAL_NET}"
fi
export ASTERISK_PJSIP_EXTERNAL_SIGNALING_LINE
export ASTERISK_PJSIP_EXTERNAL_MEDIA_LINE
export ASTERISK_PJSIP_LOCAL_NET_LINE
export ASTERISK_RTP_START
export ASTERISK_RTP_END
export UNIFI_TALK_ENDPOINT
export UNIFI_TALK_INBOUND_CONTEXT
export UNIFI_TALK_OUTBOUND_CONTEXT
export UNIFI_TALK_SIP_SERVER
export UNIFI_TALK_SIP_PORT
export UNIFI_TALK_SIP_USERNAME
export UNIFI_TALK_SIP_PASSWORD
export DOGRAH_INBOUND_EXTENSION

missing=()
[[ -n "${ASTERISK_ARI_PASSWORD}" ]] || missing+=("ASTERISK_ARI_PASSWORD")

if [[ "${ASTERISK_REQUIRE_UNIFI}" == "true" ]]; then
    [[ -n "${UNIFI_TALK_SIP_SERVER}" ]] || missing+=("UNIFI_TALK_SIP_SERVER")
    [[ -n "${UNIFI_TALK_SIP_USERNAME}" ]] || missing+=("UNIFI_TALK_SIP_USERNAME")
    [[ -n "${UNIFI_TALK_SIP_PASSWORD}" ]] || missing+=("UNIFI_TALK_SIP_PASSWORD")
fi

if (( ${#missing[@]} > 0 )); then
    printf 'Missing required Asterisk environment variables: %s\n' "${missing[*]}" >&2
    exit 64
fi

if [[ "${ASTERISK_ARI_PASSWORD}" == "dograh-change-me" ]]; then
    printf 'ASTERISK_ARI_PASSWORD must not use the public default value.\n' >&2
    exit 64
fi

mkdir -p /etc/asterisk /var/lib/asterisk /var/log/asterisk /var/run/asterisk /var/spool/asterisk

envsubst_vars='${ASTERISK_ARI_USERNAME} ${ASTERISK_ARI_PASSWORD} ${ASTERISK_STASIS_APP} ${ASTERISK_HTTP_BINDADDR} ${ASTERISK_HTTP_PORT} ${ASTERISK_WS_CLIENT_NAME} ${DOGRAH_ARI_WS_URI} ${ASTERISK_WS_TLS_ENABLED} ${ASTERISK_PJSIP_BINDADDR} ${ASTERISK_PJSIP_PORT} ${ASTERISK_EXTERNAL_SIGNALING_ADDRESS} ${ASTERISK_EXTERNAL_MEDIA_ADDRESS} ${ASTERISK_LOCAL_NET} ${ASTERISK_PJSIP_EXTERNAL_SIGNALING_LINE} ${ASTERISK_PJSIP_EXTERNAL_MEDIA_LINE} ${ASTERISK_PJSIP_LOCAL_NET_LINE} ${ASTERISK_RTP_START} ${ASTERISK_RTP_END} ${UNIFI_TALK_ENDPOINT} ${UNIFI_TALK_INBOUND_CONTEXT} ${UNIFI_TALK_OUTBOUND_CONTEXT} ${UNIFI_TALK_SIP_SERVER} ${UNIFI_TALK_SIP_PORT} ${UNIFI_TALK_SIP_USERNAME} ${UNIFI_TALK_SIP_PASSWORD} ${DOGRAH_INBOUND_EXTENSION}'

for template in /etc/asterisk/templates/*.template; do
    [[ -e "${template}" ]] || continue
    destination="/etc/asterisk/$(basename "${template%.template}")"
    envsubst "${envsubst_vars}" < "${template}" > "${destination}"
    chown asterisk:asterisk "${destination}"
done

chown -R asterisk:asterisk /var/lib/asterisk /var/log/asterisk /var/run/asterisk /var/spool/asterisk

exec "$@"
